JEVEGA_Us_Cliniic/Controllers/DiagnosticExamsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JEVEGA_Us_Cliniic;

namespace JEVEGA_Us_Cliniic.Controllers
{
    [Authorize]
    public class DiagnosticExamsController : Controller
    {
        private JEVEGA_UsDbEntities db = new JEVEGA_UsDbEntities();

        // GET: DiagnosticExams
        public ActionResult Index()
        {
            return View(db.DiagnosticExams.ToList());
        }

        // GET: DiagnosticExams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiagnosticExam diagnosticExam = db.DiagnosticExams.Find(id);
            if (diagnosticExam == null)
            {
                return HttpNotFound();
            }
            return View(diagnosticExam);
        }

        // GET: DiagnosticExams/Create
        public ActionResult Create()
        {
            string usertype = Session["USER_TYPE"].ToString();
            if (usertype == "1")   //-- Admin user ... 
            {
                ViewBag.ExamCategoryTypes = new SelectList(db.DiagnosticExamCategories, "Id", "CategoryName");
            }
            else { return RedirectToAction("UnauthorizedAccess", "Users"); }

            return View();
        } //--

        // POST: DiagnosticExams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ExamCategory,ExamName,ClinicBasePrice,DoctorBasePrice")] DiagnosticExam diagnosticExam)
        {
            if (ModelState.IsValid)
            {
                db.DiagnosticExams.Add(diagnosticExam);
                db.SaveChanges();
                CreateExamPriceHistory(diagnosticExam);
                return RedirectToAction("Index");
            }
            else
            {
                //*** if model state is not valid ... re-create list 
                ViewBag.ExamCategoryTypes = new SelectList(db.DiagnosticExamCategories, "Id", "CategoryName");
            }

            return View(diagnosticExam);
        }

        // GET: DiagnosticExams/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.ExamCategoryTypes = new SelectList(db.DiagnosticExamCategories, "Id", "CategoryName");

            if (id == null)
            {   return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }

            DiagnosticExam diagnosticExam = db.DiagnosticExams.Find(id);
            if (diagnosticExam == null)
            {   return HttpNotFound();      }

            string usertype = Session["USER_TYPE"].ToString();
            if (usertype == "1")   //-- Admin user ... 
            {
                return View(diagnosticExam);
            }
            else { return RedirectToAction("UnauthorizedAccess", "Users"); }

        } //--

        // POST: DiagnosticExams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ExamCategory,ExamName,ClinicBasePrice,DoctorBasePrice")] DiagnosticExam diagnosticExam)
        {
            if (ModelState.IsValid)
            {
                db.Entry(diagnosticExam).State = EntityState.Modified;
                db.SaveChanges();
                CreateExamPriceHistory(diagnosticExam);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ExamCategoryTypes = new SelectList(db.DiagnosticExamCategories, "Id", "CategoryName");
            }

            return View(diagnosticExam);
        } //--

        // GET: DiagnosticExams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiagnosticExam diagnosticExam = db.DiagnosticExams.Find(id);
            if (diagnosticExam == null)
            {
                return HttpNotFound();
            }
            return View(diagnosticExam);
        }

        // POST: DiagnosticExams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DiagnosticExam diagnosticExam = db.DiagnosticExams.Find(id);
            db.DiagnosticExams.Remove(diagnosticExam);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void CreateExamPriceHistory(DiagnosticExam diagnosticExam)
        {
            string US_ConnStr = ConfigurationManager.ConnectionStrings["USClinic_ADO"].ConnectionString;
            using (SqlConnection sqlCon = new SqlConnection(US_ConnStr))
            {
                SqlCommand sqlCmd = new SqlCommand();
                sqlCmd.CommandText = "Insert ExamPriceHistory(ExamCategory, ExamName, ClinicBasePrice, DoctorBasePrice, PriceDate, ExamNameId) Values(@examcat, @examname, @clprice, @docprice, @date, @examname_id)";

                sqlCmd.Parameters.AddWithValue("@examcat", diagnosticExam.ExamCategory);
                sqlCmd.Parameters.AddWithValue("@examname", diagnosticExam.ExamName);
                sqlCmd.Parameters.AddWithValue("@clprice", diagnosticExam.ClinicBasePrice);
                sqlCmd.Parameters.AddWithValue("@docprice", diagnosticExam.DoctorBasePrice);
                sqlCmd.Parameters.AddWithValue("@date", DateTime.Now);
                sqlCmd.Parameters.AddWithValue("@examname_id", diagnosticExam.Id);

                sqlCmd.Connection = sqlCon;
                sqlCon.Open();
                int rowaffected = sqlCmd.ExecuteNonQuery();
                sqlCon.Close();
            }
        } //--
    }
}

JEVEGA_Us_Cliniic/Controllers/DiagnosticServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JEVEGA_Us_Cliniic.Controllers
{
    public class DiagnosticServicesController : Controller
    {
        // GET: DiagnosticServices
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OBGyne()
        {
            return View();
        }

        public ActionResult Pelvis()
        {
            return View();
        }

        public ActionResult Abdomen()
        {
            return View();
        }

        public ActionResult Vascular()
        {
            return View();
        }

        public ActionResult Smallparts()
        {
            return View();
        }
    }


}

JEVEGA_Us_Cliniic/Controllers/PatientDataController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JEVEGA_Us_Cliniic;

namespace JEVEGA_Us_Cliniic.Controllers
{
    [Authorize]
    public class PatientDataController : Controller
    {
        private JEVEGA_UsDbEntities db = new JEVEGA_UsDbEntities();
        public static string patient_id_number = "";

        public string[] nameIndexChar = {"All", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y"};

        [Authorize]
        [OutputCache (Duration = 60)]
        // GET: PatientData
        public ActionResult Index()
        {
            string usertype;
            try
            {   usertype = Session["USER_TYPE"].ToString();     }
            catch (NullReferenceException ex)
            {
                ViewBag.NullUser = ex.Message.ToString();
                usertype = "Empty Username";
            }
            
            if (usertype == "1")   //-- Admin user ... 
            {
                //return View(db.PatientDatas.OrderBy(pd => pd.Lastname).ToList());
                //IEnumerable<PatientData> listPatients = db.PatientDatas.Where(pd => pd.Lastname.StartsWith("A")).OrderBy(l => l.Lastname).ToList();

                //.... return by default names where surname starts with "A" ....
                IEnumerable<PatientData> listPatients = db.PatientDatas.Where(p => p.Lastname.StartsWith("A")).OrderBy(l => l.Lastname).ToList();

                //IQueryable<PatientData> listPatients = db.PatientDatas.AsQueryable().OrderBy(l => l.Lastname);

                int countPatients = listPatients.Count();
                int oldestAge = (int)listPatients.Max(p => p.Age);
                PatientData oldestPatient = listPatients.FirstOrDefault(p => p.Age == 60);

                ViewBag.IndexNameChar = nameIndexChar;

                return View(listPatients);
            }
            else { return RedirectToAction("UnauthorizedAccess", "Users"); }

        } //--

        [OutputCache (Duration = 60, VaryByParam = "id")]
        public ActionResult IndexSurname(string id)
        {
            IEnumerable<PatientData> listPatientsBySNameIndex;

            if (id == "All")
            {
                listPatientsBySNameIndex = db.PatientDatas.OrderBy(p => p.Lastname).ToList();
            }
            else {
                listPatientsBySNameIndex = db.PatientDatas.Where(p => p.Lastname.StartsWith(id)).OrderBy(p => p.Lastname).ToList();
            }

            ViewBag.IndexNameChar = nameIndexChar;
            ViewBag.IndexAlpha = id.ToString();

            return View(listPatientsBySNameIndex);
        }

        public ActionResult ListPatient()
        {
            if (Session["USER_TYPE"] == null)
            {
                return RedirectToAction("Login", "Users");
            }

            string usertype = Session["USER_TYPE"].ToString();
            if (usertype != "1")   //-- Admin user ... 
            {
                return RedirectToAction("UnauthorizedAccess", "Users");
            }

            ViewBag.IndexNameChar = nameIndexChar;
            return View();

        } //--

        // GET: PatientData/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientData patientData = db.PatientDatas.Find(id);
            if (patientData == null)
            {
                return HttpNotFound();
            }

            ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");
            List<SelectListItem> genderList = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
            genderList.Add(item1);
            SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
            genderList.Add(item2);
            ViewBag.GenderList = genderList;

            return View(patientData);
        }

        // GET: PatientData/Create
        public ActionResult Create()
        {
            ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");

            List<SelectListItem> genderList = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
            genderList.Add(item1);
            SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
            genderList.Add(item2);
            ViewBag.GenderList = genderList;

            return View();
        }

        // POST: PatientData/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Patient_Id,Lastname,Firstname,Age,Sex,Address,Email,Phone,Status,LMP")] PatientData patientData, FormCollection frmCollection)
        {
            if (ModelState.IsValid)
            {
                string patientId = patientData.Patient_Id;
                bool patientIdExist = checkPatientExamIdExist(patientId);
                string createExam = frmCollection["chkExam"].ToUpper();

                if (patientIdExist)
                {
                    ViewBag.ErrorDuplicatePatientId = "Patient  Id No. " + patientId + " already existed!  Please enter a different Id number.";
                }
                else {
                    db.PatientDatas.Add(patientData);
                    db.SaveChanges();

                    if (createExam == "ON") {
                        return RedirectToAction("Create", "PatientExam", new { p_id = patientData.Patient_Id, lmp = patientData.LMP } );
                    }
                    return RedirectToAction("Index");
                }
            }

            ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");

            List<SelectListItem> genderList = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
            genderList.Add(item1);
            SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
            genderList.Add(item2);
            ViewBag.GenderList = genderList;

            return View(patientData);
        }
         
        // GET: PatientData/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientData patientData = db.PatientDatas.Find(id);
            if (patientData == null)
            {
                return HttpNotFound();
            }

            ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");
            List<SelectListItem> genderList = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
            genderList.Add(item1);
            SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
            genderList.Add(item2);
            ViewBag.GenderList = genderList;

            patient_id_number = patientData.Patient_Id.ToString();
            return View(patientData);
        }

        // POST: PatientData/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Patient_Id,Lastname,Firstname,Age,Sex,Address,Email,Phone,LoginPassword,Status,LMP")] PatientData patientData)
        {
            patientData.Patient_Id = patient_id_number;

            if (ModelState.IsValid)
            {
                db.Entry(patientData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details/" + patientData.Id.ToString());
            }
            else {
                ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");
                List<SelectListItem> genderList = new List<SelectListItem>();
                SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
                genderList.Add(item1);
                SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
                genderList.Add(item2);
                ViewBag.GenderList = genderList;
            }
            return View(patientData);
        }

        // GET: PatientData/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientData patientData = db.PatientDatas.Find(id);
            if (patientData == null)
            {
                return HttpNotFound();
            }
            return View(patientData);
        }

        // POST: PatientData/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            PatientData patientData = db.PatientDatas.Find(id);
            db.PatientDatas.Remove(patientData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);

JEVEGA_Us_Cliniic/Views/Shared/Layout_inner_page.cshtml
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="An Ultrasound Clinic that offers general ultrasound examination.">
<meta name="keywords" content="ultrasound, ob, obgyne, pelvis, vascular study, small parts, diagnostic">

<title>@ViewBag.Title - JEVEGA Diagnostic Ultrasound Clinic</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>

        .navbar-inverse {
            background-color: #065ca9 !important;
            border-color: #065ca9;
        }

        .menu_text {
            font-size: 1.00em;
            color: white !important;
        }

            .menu_text:hover {
                color: #08C1B1 !important;
                text-decoration: none;
            }

        .welcome_hd {
            font-size: 0.90em;
            color: white !important;
            padding-top: 20px;
        }

        .welcome_hd_div {
            float: right;
            padding-top: 7px;
        }
    </style>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>


<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("JDUC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About The Clinic", "About", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Diagnostic Service&nbsp;<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("OB", "OBGyne", "DiagnosticServices")</a></li>
                            <li>@Html.ActionLink("Pelvis Male \\ Female", "Pelvis", "DiagnosticServices")</a></li>
                            <li>@Html.ActionLink("Abdomen (Adult \\ Pediatric)", "Abdomen", "DiagnosticServices")</a></li>
                            <li>@Html.ActionLink("Vascular Study", "Vascular", "DiagnosticServices")</a></li>
                            <li>@Html.ActionLink("Small Parts", "Smallparts", "DiagnosticServices")</a></li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("Vision", "Vision", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Finance&nbsp;<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Monthly Sales", "MonthlySales", "PatientExam")</li>
                            <li>@Html.ActionLink("Cash Disbursement", "Index", "CashDisbursement")</li>
                            <li>@Html.ActionLink("Sales Summary", "SalesSummary", "PatientExam")</li>
                            <li><hr /></li>
                            <li>@Html.ActionLink("Doctor's PF", "DoctorsPF", "PatientExam")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Clinic Admin&nbsp;<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Patient Data", "Index", "PatientData")</li>
                            <li>@Html.ActionLink("Patient Exam", "Index", "PatientExam")</li>
                            <li>@Html.ActionLink("Diagnostic Exam", "Index", "DiagnosticExams")</li>
                            <li>@Html.ActionLink("Diagnostic Exam Category", "Index", "DiagnosticExamCategories")</li>
                            <li>@Html.ActionLink("Report Template", "Index", "ReportTemplates")</li>
                            <li>@Html.ActionLink("Exam Video", "Index", "ExamVideo")</li>
                            <li><hr /></li>
                            <li>@Html.ActionLink("Radiologist", "Index", "RadDoctor")</li>
                            <li>@Html.ActionLink("Sonographer", "Index", "Sonographers")</li>
                            <li><hr /></li>
                            <li>@Html.ActionLink("Admin Users", "Index", "Users")
                        </ul>
                    </li>
                    <li>
                        @if (Session["USER_ID"] != null)
                        {
                            <div class="row" style="padding:10px;">
                                <div class="col-md-12">
                                    <table>
                                        <tr>
                                            <td><img src="~/images/log_user_icon.png" /></td>
                                            <td>&nbsp;<a href="/Users/Logout" class="menu_text">Logout</a></td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        }
                    </li>
                </ul>

                @if (Session["USER_NAME"] != null)
                {
                    <div class="welcome_hd_div">
                        <span class="welcome_hd">Welcome to JDUC @Session["USER_NAME"]!</span>
                    </div>
                }

            </div>


        </div>
    </div>

    <div class="container">
        <img class="img-responsive" src="~/images/US_web_banner_inner.jpg" />
        <hr />
    </div>

    @{
        if (ViewBag.PageViewMode == 2) //** split view ----
        {
            <div class="container-fluid body-content">
                @RenderBody()
            </div>
        }
        else  //** normal view ----
        {   <div class="container body-content">
                @RenderBody()
            </div>
        }
    }

    <div class="container-fluid" style="background-color:#08c1b1">
        <br />
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-2">
                            <img class="img-responsive" src="~/images/timing_icon.png" />
                        </div>
                        <div class="col-md-10">
                            <h4>Our Timing</h4>
                            <p>
                                Mon - Wed - Fri : 10:00 PM - 5:00 PM <br />
                                Tue - Thu - Sat : 2:00 PM - 5:00 PM
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-2">
                            <img class="img-responsive" src="~/images/location_icon_ii.png" />
                        </div>
                        <div class="col-md-10">
                            <h4>Our Location</h4>
                            <p>
                                317 Roosevelt Ave. EDSA Munoz Quezon City <br />
                                RADA bldg. 3rd Floor Room 304
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-2">
                            <img class="img-responsive" src="~/images/call_or_text_icon.png" />
                        </div>
                        <div class="col-md-10">
                            <h4>Call or Text Us</h4>
                            <p>
                                SMART No. 0998 2547187<br />
                                GLOBE No. 0915 0333214
                            </p>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <br />
    </div>

    <!-- footer -->
    <div class="container-fluid" style="background-color:#bbbfca">
        <div class="container">
            <br />
            <div class="row">
                <div class="col-md-10">
                    <footer><p>&copy; @DateTime.Now.Year JEVEGA Diagnostic Ultrasound Clinic</p></footer>
                </div>
                <div class="col-md-2">
                    <table class="">
                        <tr>
                            <td><a href="https://www.facebook.com/jevega.us" target="_blank"><img src="~/images/facebook_logo_icon.png" /></a></td>
                            <td style="width:20px;"></td>
                            <td>
                                <img src="~/images/youtube_logo_icon.png" />
                            </td>
                            <td style="width:20px;"></td>
                            <td>
                                <img src="~/images/instagram_logo_icon.png" />
                            </td>
                        </tr>
                    </table>

                </div>
            </div>
            <br />
        </div>
    </div>


    <div class="sidemenu_div">

        <table>
            <tr>
                <td>
                    <a href="/PatientData/Index"><img src="~/images/patient_data_icon.png" border="0" /></a>
                </td>
            </tr>
            <tr><td><div class="div_space20"></div></td></tr>
            <tr>
                <td>
                    <a href="/PatientExam/Index"><img src="~/images/patient_exam_icon.png" border="0" /></a>
                </td>
            </tr>
            <tr><td><div class="div_space20"></div></td></tr>
            <tr>
                <td>
                    <a href="/DiagnosticExams/Index"><img src="~/images/diagnostic_exam_category_icon.png" border="0" /></a>
                </td>
            </tr>
        </table>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

JEVEGA_Us_Cliniic/Views/Shared/Layout_print_image.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="An Ultrasound Clinic that offers general ultrasound examination.">
    <meta name="keywords" content="ultrasound, ob, obgyne, pelvis, vascular study, small parts, diagnostic">

    <title>@ViewBag.Title - JEVEGA Diagnostic Ultrasound Clinic</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        body {
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            padding-bottom: 20px;
            padding-top: 20px;
        }

        .navbar-inverse {
            background-color: #065ca9 !important;
            border-color: #065ca9;
        }

        .menu_text {
            font-size: 1.00em;
            color: white !important;
        }
    </style>

</head>

<body>

    <div class="container">
        <img class="img-responsive" src="~/images/US_web_banner_inner.jpg" />
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

JEVEGA_Us_Cliniic/Views/Shared/Layout_print_report.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="An Ultrasound Clinic that offers general ultrasound examination.">
    <meta name="keywords" content="ultrasound, ob, obgyne, pelvis, vascular study, small parts, diagnostic">

    <title>@ViewBag.Title - JEVEGA Diagnostic Ultrasound Clinic</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        body {
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            padding-bottom: 20px;
            padding-top: 10px;
            background-color: #fff;
        }

        .navbar-inverse {
            background-color: #065ca9 !important;
            border-color: #065ca9;
        }

        .report_logo {
            height: 80px;
        }

        .div_iconbg {
            position: fixed;
            bottom: 0;
            right: 0;
            opacity: .70;
            padding-bottom: 10px;
            padding-right: 10px;
        }

        .div_footer {
            position: fixed;
            bottom: 0;
            left: 0;
            padding-bottom: 10px;
            padding-left: 10px;
        }

    </style>

</head>

<body>

    <div class="container">
        <img class="img-responsive report_logo" src="~/images/UsLogo_print_ii.png" />
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    <div class="div_iconbg">
        <img src="~/images/ultrasound-icon.png" />
    </div>

    <div class="div_footer">
        <span class="table_field_value">317 Roosevelt Ave. EDSA Munoz Q.C. RADA bldg. 3rd Floor Room 304 | SMART No. 0998 2547187 </span>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>