JEVEGA_Us_Cliniic/Controllers/PatientExamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JEVEGA_Us_Cliniic;
using System.IO;
using System.Configuration;
using System.Data.SqlClient;

namespace JEVEGA_Us_Cliniic.Controllers
{
    [Authorize]
    public class PatientExamController : Controller
    {
        private JEVEGA_UsDbEntities db = new JEVEGA_UsDbEntities();
        UtilityHelper utHelp = new UtilityHelper();

        public string[] fullMonthName = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };

        // GET: PatientExam
        public ActionResult Index()
        {
            if (Session["USER_TYPE"] == null)
            {
                return RedirectToAction("Login", "Users", new { @ReturnUrl = "/PatientExam/Index" });
            }

            string query_month = Request.QueryString["mo"];
            string query_year = Request.QueryString["yr"];

            int this_month;
            int this_year;
            if (query_month == null)
            {
                DateTime today = DateTime.Now;
                this_month = today.Month;
                this_year = today.Year;
            }
            else
            {   this_month = Convert.ToInt32(query_month);
                this_year = Convert.ToInt32(query_year);
            }

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            listOfYears = utHelp.CreateListOfYears(this_year);

            ViewBag.YearsList = listOfYears.ToList();
            //...............................................................................................

            List<SelectListItem> listOfMonths = new List<SelectListItem>();
            listOfMonths = utHelp.CreateListMonthNames(this_month);

            ViewBag.MonthsList = listOfMonths.ToList();
            ViewBag.DateList = fullMonthName[this_month - 1] + " " + this_year;

            ViewBag.SelectedMonth = this_month;
            ViewBag.SelectedYear = this_year;
            //...............................................................................................

            List<PatientExam> patientExamList = db.PatientExams.Where(p => p.ExamDate.Value.Month == this_month && p.ExamDate.Value.Year == this_year).ToList();

            //return View(db.PatientExams.ToList());
            return View(patientExamList);

        } //-- 

        [HttpPost]
        public ActionResult Index(FormCollection formCollection)
        {
            string str_year = formCollection["ListOfYears"];
            int this_year = Convert.ToInt32(str_year);

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            listOfYears = utHelp.CreateListOfYears(this_year);

            ViewBag.YearsList = listOfYears.ToList();
            //...............................................................................................
            string str_month = formCollection["ListOfMonths"];
            int this_month = Convert.ToInt32(str_month);

            List<SelectListItem> listOfMonths = new List<SelectListItem>();
            listOfMonths = utHelp.CreateListMonthNames(this_month);

            ViewBag.MonthsList = listOfMonths.ToList();
            ViewBag.DateList = fullMonthName[this_month - 1] + " " + this_year;

            ViewBag.SelectedMonth = this_month;
            ViewBag.SelectedYear = this_year;
            //...............................................................................................

            List<PatientExam> patientExamList = db.PatientExams.Where(p => p.ExamDate.Value.Month == this_month && p.ExamDate.Value.Year == this_year).ToList();

            return View(patientExamList);
        } //-- 

        public ActionResult DoctorsPF()
        {
            if (Session["USER_TYPE"] == null)
            {
                return RedirectToAction("Login", "Users", new { @ReturnUrl = "/PatientExam/Index" });
            }

            string query_month = Request.QueryString["mo"];
            string query_year = Request.QueryString["yr"];

            int this_month;
            int this_year;
            if (query_month == null)
            {
                DateTime today = DateTime.Now;
                this_month = today.Month;
                this_year = today.Year;
            }
            else
            {
                this_month = Convert.ToInt32(query_month);
                this_year = Convert.ToInt32(query_year);
            }

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            listOfYears = utHelp.CreateListOfYears(this_year);

            ViewBag.YearsList = listOfYears.ToList();
            //...............................................................................................

            List<SelectListItem> listOfMonths = new List<SelectListItem>();
            listOfMonths = utHelp.CreateListMonthNames(this_month);

            ViewBag.MonthsList = listOfMonths.ToList();
            ViewBag.DateList = fullMonthName[this_month-1] + " " + this_year;
            //...............................................................................................

            List<PatientExam> patientExamList = db.PatientExams.Where(p => p.ExamDate.Value.Month == this_month && p.ExamDate.Value.Year == this_year).ToList();

            int? totalAmount = patientExamList.Sum(a => a.getDoctorsExamPrice);
            double? totalPF = patientExamList.Sum(a => a.getDoctorsPF);

            string strTotalAmount = string.Format("{0:0.00}", totalAmount);
            string strTotalPF = string.Format("{0:0.00}", totalPF);

            ViewBag.TotalSalesAmount = strTotalAmount;
            ViewBag.TotalDoctorsPF = strTotalPF;
            ViewBag.MonthReport = this_month;

            return View(patientExamList);
        } //--

        [HttpPost]
        public ActionResult DoctorsPF(FormCollection formCollection)
        {
            string str_year = formCollection["ListOfYears"];
            int this_year = Convert.ToInt32(str_year);

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            listOfYears = utHelp.CreateListOfYears(this_year);

            ViewBag.YearsList = listOfYears.ToList();
            //...............................................................................................
            string str_month = formCollection["ListOfMonths"];
            int this_month = Convert.ToInt32(str_month);

            List<SelectListItem> listOfMonths = new List<SelectListItem>();
            listOfMonths = utHelp.CreateListMonthNames(this_month);

            ViewBag.MonthsList = listOfMonths.ToList();
            ViewBag.DateList = fullMonthName[this_month - 1] + " " + this_year;
            //...............................................................................................
            List<PatientExam> patientExamList = db.PatientExams.Where(p => p.ExamDate.Value.Month == this_month && p.ExamDate.Value.Year == this_year).ToList();

            int? totalAmount = patientExamList.Sum(a => a.getDoctorsExamPrice);
            double? totalPF = patientExamList.Sum(a => a.getDoctorsPF);

            string strTotalAmount = string.Format("{0:0.00}", totalAmount);
            string strTotalPF = string.Format("{0:0.00}", totalPF);

            ViewBag.TotalSalesAmount = strTotalAmount;
            ViewBag.TotalDoctorsPF = strTotalPF;
            ViewBag.MonthReport = this_month;

            return View(patientExamList);

        } //==

        public ActionResult PrintDoctorsPF(int month_id)
        {
            string[] monthName = {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
            DateTime today = DateTime.Now;
            string yearReport = today.Year.ToString();

            List<PatientExam> patientExamList = db.PatientExams.Where(p => p.ExamDate.Value.Month == month_id).ToList();

            int? totalAmount = patientExamList.Sum(a => a.getDoctorsExamPrice);
            double? totalPF = patientExamList.Sum(a => a.getDoctorsPF);

            string strTotalAmount = string.Format("{0:0.00}", totalAmount);
            string strTotalPF = string.Format("{0:0.00}", totalPF);

            ViewBag.TotalSalesAmount = strTotalAmount;
            ViewBag.TotalDoctorsPF = strTotalPF;
            ViewBag.ReportDate = monthName[month_id - 1] + " " + yearReport;

            return View(patientExamList);
        } //--

        public ActionResult MonthlySales()
        {
            if (Session["USER_TYPE"] == null)
            {
                return RedirectToAction("Login", "Users", new { @ReturnUrl = "/PatientExam/Index" });
            }

            string query_month = Request.QueryString["mo"];
            string query_year = Request.QueryString["yr"];

            int this_month;
            int this_year;
            if (query_month == null)
            {
                DateTime today = DateTime.Now;
                this_month = today.Month;
                this_year = today.Year;
            }
            else
            {   this_month = Convert.ToInt32(query_month);
                this_year = Convert.ToInt32(query_year);
            }

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            listOfYears = utHelp.CreateListOfYears(this_year);

            List<SelectListItem> listOfMonths = new List<SelectListItem>();
            listOfMonths = utHelp.CreateListMonthNames(this_month);

            ViewBag.YearsList = listOfYears.ToList();
            ViewBag.MonthsList = listOfMonths.ToList();
            ViewBag.DateList = fullMonthName[this_month - 1] + " " + this_year;
            //...............................................................................................

JEVEGA_Us_Cliniic/Views/PatientExam/Index.cshtml
@model IEnumerable<JEVEGA_Us_Cliniic.PatientExam>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Patient Exams List | @ViewBag.DateList</h3></td>
        <td align="right">
            @{   
                if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Create", "PatientExam")><img src="~/images/add_icon.png" /></a>
                }
            }
            &nbsp;
        </td>
    </tr>
</table>
<div class="div_space20"></div>


<table class="table table-striped">
    <tr>
        <th>@Html.DisplayNameFor(model => model.PatientID)</th>
        <th>@Html.DisplayNameFor(model => model.ExamId)</th>
        <th>@Html.DisplayNameFor(model => model.ExamType)</th>
        <th>@Html.DisplayNameFor(model => model.ExamDate)</th>
        @*<th>@Html.DisplayNameFor(model => model.Sonographer)</th>*@
        <th>@Html.DisplayNameFor(model => model.Radiologist)</th>
        <th>Images</th>
        <th>@Html.DisplayNameFor(model => model.SignByDoctor)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.getPatientName)</td>
        <td>@Html.DisplayFor(modelItem => item.ExamId)</td>
        <td>@Html.DisplayFor(modelItem => item.getExamName)</td>
        <td>@Html.DisplayFor(modelItem => item.ExamDate)</td>
        @*<td>@Html.DisplayFor(modelItem => item.getSonographerName)</td>*@
        <td>@Html.DisplayFor(modelItem => item.getDoctorName)</td>

        <td><span class="text_form_value">@item.IsExamImagesExist()</span></td>

        <td>
            @if (item.SignByDoctor == "Y")
            {<span class="text_form_value_ii">@Html.DisplayFor(modelItem => item.getSignDefinition)</span>}
        else
        { <span class="text_form_value">@Html.DisplayFor(modelItem => item.getSignDefinition)</span>}
        </td>

        <td>
            @if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
            {
                <a href=@Url.Action("Edit", new { id = item.Id }) alt="Edit"><img src="~/images/edit_ico.png" /></a>

                <a href=@Url.Action("InitialReport", new { id = item.Id }) alt="Edit"><img src="~/images/report_initial.png" /></a>
            }
            - <a href=@Url.Action("Details", new { id = item.Id }) alt="Details"><img src="~/images/details_ico.png" /></a>
            - <a href=@Url.Action("ScanImages", new { id = item.Id }) alt="Details"><img src="~/images/scan_images_icon.png" /></a>
            - <a href=@Url.Action("SignMedicalReport", new { id = item.Id }) alt="Sign Report"><img src="~/images/sign_doc_ico.png" /></a>
        </td>
    </tr>
    }

</table>

@using (Html.BeginForm())
{

<table class="table table-bordered">
<tr>
    <td nowrap="nowrap">
        @Html.DropDownList("ListOfMonths", (List<SelectListItem>)ViewBag.MonthsList, "- Select an Month -", new { @class = "form-control" })
    </td>
    <td>
        @Html.DropDownList("ListOfYears", (List<SelectListItem>)ViewBag.YearsList, "- Select a Year -", new { @class = "form-control" })
    </td>
    <td>
        <input type="submit" value="Filter by Month/Year" class="btn btn-default" />
    </td>
    <td>
        <input type="button" value="Show Monthly Sales" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("MonthlySales", "PatientExam", new { mo=ViewBag.SelectedMonth, yr=ViewBag.SelectedYear }) + "'");" />
    </td>
</tr>
</table>


<div class="div_space20"></div>

}

JEVEGA_Us_Cliniic/Views/PatientExam/PrintExamReport.cshtml
@model JEVEGA_Us_Cliniic.PatientExam

@{
    ViewBag.Title = "PrintExamReport";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}


@using (Html.BeginForm(null, null, FormMethod.Post, new { @action = @Url.Action("PrintReportWithLogo\\" + Model.Id, "PatientExam"), target = "_blank" }))
{
    @Html.AntiForgeryToken()

    <div>
        <div style="float:right">
            <span class="report_text2">Report Date : @Html.DisplayFor(model => model.formattedExamDate)</span>
        </div>

        <div class="div_space20"></div>
        <table class="table-bordered table_clinic">
            <tr>
                <td style="width:140px;"><span class="report_text1" style="padding:7px;">Patient Name:</span></td>
                <td colspan="2"><span class="report_text1">@Html.DisplayFor(model => model.getPatientName)</span></td>
                <td style="width:140px;">
                    <div style="padding:7px;"><span class="report_text1">Exam Id:</span></div>
                </td>
                <td><span class="report_text1">@Html.DisplayFor(model => model.ExamId)</span></td>
            </tr>

            <tr>
                <td><div style="padding:7px;"><span class="print_label">Sex:</span></div></td>
                <td><span class="print_value">@ViewBag.PatientSex</span></td>
                <td><span class="print_label" style="padding:7px;">Age:&nbsp;&nbsp;@ViewBag.Age</span></td>
                <td><span class="print_label" style="padding:7px;">Marital Status:</span></td>
                <td><span class="print_value">@ViewBag.Status</span></td>
            </tr>
        </table>

        <div class="div_space20"></div>
        <div><span class="report_text1">History</span></div>
        <div class="line_space"></div>
        <div class="line_space"></div>

        <table class="table-bordered table_clinic">
            <tr>
                <td style="vertical-align:top;">
                    <div class="div_textarea">
                        <textarea class="textarea_exam_history" readonly >@Html.DisplayFor(model => model.History)</textarea>
                    </div>
                </td>
            </tr>
        </table>

        <div class="div_space20"></div>
        <div><span class="report_text1">Exam : @Html.DisplayFor(model => model.getExamName)</span></div>
        <div class="line_space"></div>
        <div class="line_space"></div>

        <table class="table-bordered table_clinic" style="height:120px;">
            <tr>
                <td style="vertical-align:top;">
                    <div class="div_textarea">
                        <textarea class="textarea_exam_report" readonly >@ViewBag.ExamReport</textarea>
                    </div>
                </td>
            </tr>
        </table>

        <div class="div_space20"></div>
        <div class="div_space20"></div>
        <div class="div_space20"></div>
        <div class="div_space20"></div>

        <div>
            <table class="table_clinic">
                <tr>
                    <td><img src="~/ClinicStaff/sign-1.jpg" style="width:200px;" /></td>
                </tr>
                <tr><td><div class="line_space"></div></td></tr>
                <tr>
                    <td>
                        <span class="report_text2">Report by: Dr. @Html.DisplayFor(model => model.getDoctorFistLastName) - @Html.DisplayFor(model => model.getDoctorPostTitle)</span><br />
                        <span class="report_text2">PRC License No. : @Html.DisplayFor(model => model.getDoctorPRCLicenseNo)</span>
                    </td>
                </tr>
            </table>
        </div>


        <div class="div_space20"></div>
        <div class="div_space20"></div>
        <div class="line_space"></div>
        <table class="table table-bordered">
        <tr>
            <td>
                <input type="submit" value="Print Normal Template" class="btn btn-default" />
                &nbsp;
                <input type="button" value="Print OB Template" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action(ViewBag.PrintReportTemplate, "PatientExam", new { id = Model.Id}) + "'");" />
                &nbsp;
                <input type="button" value="Print In LetterHead" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("PrintReportLetterHead", "PatientExam") + "'");" />
                &nbsp;
                <input type="button" value="Send to OB Doctor" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("SendExamReportToOBDoctor\\" + Model.Id, "PatientExam") + "'");" />
                &nbsp;
                @if (ViewBag.PatientHasEmail)
                {
                    <input type="button" value="Send to Patient" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("SendExamReportToPatient", "PatientExam", new { id = Model.Id}) + "'");" />
                }
                &nbsp;
                <input type="button" value="Back to Details" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Details", "PatientExam", new { id = Model.Id}) + "'");" />
            </td>
        </tr>
        </table>

    </div>

    }

JEVEGA_Us_Cliniic/Views/PatientExam/PrintOBTemplate.cshtml
@model JEVEGA_Us_Cliniic.PatientExam

@{
    ViewBag.Title = "Print In OB Template";
    Layout = "~/Views/Shared/" + ViewBag.PrintLayout;
}


@using (Html.BeginForm(null, null, FormMethod.Post, new { @action = @Url.Action("PrintOBTemplate", "PatientExam", new { id = Model.Id, layout = 2 }), target = "_blank" }))
{
  @Html.AntiForgeryToken()

<div>
    <div style="float:right">
        <span class="report_text2">Report Date : @Html.DisplayFor(model => model.formattedExamDate)</span>
    </div>

    <div class="div_space20"></div>
    <table class="table-bordered table_clinic">
        <tr>
            <td style="width:140px;"><span class="report_text1" style="padding:7px;">Patient Name:</span></td>
            <td colspan="2"><span class="report_text1">@Html.DisplayFor(model => model.getPatientName)</span></td>
            <td style="width:140px;">
                <div style="padding:7px;"><span class="report_text1">Exam Id:</span></div>
            </td>
            <td><span class="report_text1">@Html.DisplayFor(model => model.ExamId)</span></td>
        </tr>

        <tr>
            <td><div style="padding:7px;"><span class="print_label">Sex:</span></div></td>
            <td><span class="print_value">@ViewBag.PatientSex</span></td>
            <td><span class="print_label" style="padding:7px;">Age:&nbsp;&nbsp;@ViewBag.Age</span></td>
            <td><span class="print_label" style="padding:7px;">Marital Status:</span></td>
            <td><span class="print_value">@ViewBag.Status</span></td>
        </tr>
    </table>

    <div class="div_space20"></div>
    <div><span class="report_text1">History</span></div>
    <div class="line_space"></div>
    <div class="line_space"></div>

    <table class="table-bordered table_clinic">
    <tr>
        <td style="vertical-align:top;">
            <div class="div_textarea">
                <textarea class="textarea_exam_report_print" rows="@ViewBag.LineCountHistory" readonly>@Html.DisplayFor(model => model.History)</textarea>
            </div>
        </td>
    </tr>
    </table>

    <div class="div_space20"></div>
    <div><span class="report_text1">Exam : @Html.DisplayFor(model => model.getExamName)</span></div>
    <div class="line_space"></div>
    <div class="line_space"></div>

    <p><span class="textarea_exam_report">@ViewBag.InitialReport</span></p>

    <table class="table-bordered table_clinic" style="width:100%;">
        <tr>
            <td width="25%"><span class="report_text1">@ViewBag.BPDvalue</span></td>
            <td width="25%"><span class="report_text1">@ViewBag.HCvalue</span></td>
            <td width="25%"><span class="report_text1">@ViewBag.ACvalue</span></td>
            <td width="25%"><span class="report_text1">@ViewBag.FLvalue</span></td>
        </tr>
    </table>

    <div class="line_space"></div>
    <div class="line_space"></div>

    @{ if (ViewBag.CRLvalue != "0")
        {
            <table class="table-bordered table_clinic" style="width:100%;">
            <tr>
                <td width="25%"><span class="report_text1">@ViewBag.CRLvalue</span></td>
                <td width="25%"><span class="report_text1">@ViewBag.AFVvalue</span></td>
                <td width="25%"><span class="report_text1">@ViewBag.EFBWvalue</span></td>
                <td width="25%"><span class="report_text1">@ViewBag.FHRvalue</span></td>
            </tr>
            </table>
        }
        else
        {
            <table class="table-bordered table_clinic" style="width:100%;">
            <tr>
                <td width="25%"><span class="report_text1">@ViewBag.AFVvalue</span></td>
                <td width="25%"><span class="report_text1">@ViewBag.EFBWvalue</span></td>
                <td width="25%"><span class="report_text1">@ViewBag.FHRvalue</span></td>
                <td width="25%"><span class="report_text1">&nbsp;</span></td>
            </tr>
            </table>
        }
    }

    <div class="line_space"></div>
    <div class="line_space"></div>

    <table class="table-bordered table_clinic">
        <tr>
            <td style="vertical-align:top;">
                <div class="div_textarea">
                    <textarea class="textarea_exam_report_print" rows="@ViewBag.LineCount" readonly>@ViewBag.ClosingReport</textarea>
                </div>
            </td>
        </tr>
    </table>

    <div class="div_space20"></div>
    <div class="div_space20"></div>
    <div class="div_space20"></div>
    <div class="div_space20"></div>

    <div>
        <table class="table_clinic">
            <tr>
                <td><img src="~/ClinicStaff/sign-1.jpg" style="width:200px;" /></td>
            </tr>
            <tr><td><div class="line_space"></div></td></tr>
            <tr>
                <td>
                    <span class="report_text2">Report by: Dr. @Html.DisplayFor(model => model.getDoctorFistLastName) - @Html.DisplayFor(model => model.getDoctorPostTitle)</span><br />
                    <span class="report_text2">PRC License No. : @Html.DisplayFor(model => model.getDoctorPRCLicenseNo) | Radiologist / Sonologist</span>
                </td>
            </tr>
        </table>
    </div>

    @if (ViewBag.PrintLayout == "Layout_inner_page.cshtml")
    {
        <div class="div_space20"></div>
        <div class="div_space20"></div>
        <div class="line_space"></div>
        <table class="table table-bordered">
            <tr>
                <td>
                    <input type="submit" value="Print In OB Template" class="btn btn-default" />
                    &nbsp;
                    <input type="button" value="Back to Details" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Details", "PatientExam", new { id = Model.Id}) + "'");" />
                </td>
            </tr>
        </table>
    }

</div>

}

JEVEGA_Us_Cliniic/Views/PatientExam/SendExamReportToOBDoctor.cshtml
@{
    ViewBag.Title = "SendExamReportToOBDoctor";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h3>Send to OB Doctor - Diagnostic Official Report</h3>

@if (!ViewBag.Posted)
{
    <hr />
    using (Html.BeginForm())
    {
        <input type="hidden" id="mail_ob_doctor" name="mail_ob_doctor" value="@ViewBag.OBDoctorEmail" />

        <div>
            <textarea id="mail_subject" name="mail_subject" class="textarea_report" rows="1">@ViewBag.MailSubject</textarea>
        </div>

        <div class="div_space20"></div>

        <div>
            <textarea id="mail_body" name="mail_body" class="textarea_report" rows="14">@ViewBag.MailBody</textarea>
        </div>

        <div class="div_space20"></div>

        <div style="float:right">
            <input type="submit" value="Send Mail" class="btn btn-default" />
            &nbsp;
            <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Details/" + ViewBag.PatientExamId, "PatientExam") + "'");" />
        </div>

        <div class="div_space20"></div>
        <div class="div_space20"></div>
    }
}

<span class="error_message">@ViewBag.ResponseMessage</span>
<div class="div_space20"></div>

JEVEGA_Us_Cliniic/Views/PatientExam/SendExamToRadiologist.cshtml
@{
    ViewBag.Title = "SendExamToRadiologist";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h3>Send Mail Notification to Radiologist</h3>

@if (!ViewBag.Posted)
{
  <hr />
  using (Html.BeginForm())
  {
    <input type="hidden" id="mail_rad_doctor" name="mail_rad_doctor" value="@ViewBag.RadDoctorEmail" />

    <div>
        <textarea id="mail_subject" name="mail_subject" class="textarea_report" rows="1">@ViewBag.MailSubject</textarea>
    </div>

    <div class="div_space20"></div>

    <div>
        <textarea id="mail_body" name="mail_body" class="textarea_report" rows="14">@ViewBag.MailBody</textarea>
    </div>

    <div class="div_space20"></div>

    <div style="float:right">
        <input type="submit" value="Send Mail" class="btn btn-default" />
        &nbsp;
        <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Details/" + ViewBag.PatientExamId, "PatientExam") + "'");" />
    </div>

    <div class="div_space20"></div>
    <div class="div_space20"></div>
  }
}

<span class="error_message">@ViewBag.ResponseMessage</span>
<div class="div_space20"></div>

JEVEGA_Us_Cliniic/Views/PatientExam/ShowPatientExam.cshtml
@model IEnumerable<JEVEGA_Us_Cliniic.PatientExam>

@{
    ViewBag.Title = "ShowPatientExam";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}


<table class="table_clinic_pageheader">
<tr>
    <td><h3>Exams List for Patient : @ViewBag.PatientName  </h3></td>
    <td align="right">
        @{
            if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
            {
                <a href=@Url.Action("Create", "PatientExam")><img src="~/images/add_icon.png" /></a>
            }
        }
        &nbsp;
    </td>
</tr>
</table>
<div class="div_space20"></div>


<table class="table table-striped">
    <tr>
        <th>@Html.DisplayNameFor(model => model.PatientID)</th>
        <th>@Html.DisplayNameFor(model => model.ExamId)</th>
        <th>@Html.DisplayNameFor(model => model.ExamType)</th>
        <th>@Html.DisplayNameFor(model => model.ExamDate)</th>
        <th>@Html.DisplayNameFor(model => model.Sonographer)</th>
        <th>@Html.DisplayNameFor(model => model.Radiologist)</th>
        <th>@Html.DisplayNameFor(model => model.SignByDoctor)</th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.getPatientName)</td>
            <td>@Html.DisplayFor(modelItem => item.ExamId)</td>
            <td>@Html.DisplayFor(modelItem => item.getExamName)</td>
            <td>@Html.DisplayFor(modelItem => item.ExamDate)</td>
            <td>@Html.DisplayFor(modelItem => item.getSonographerName)</td>
            <td>@Html.DisplayFor(modelItem => item.getDoctorName)</td>

            <td>
                @if (item.SignByDoctor == "Y")
                {<span class="text_form_value_ii">@Html.DisplayFor(modelItem => item.getSignDefinition)</span>}
            else
            { <span class="text_form_value">@Html.DisplayFor(modelItem => item.getSignDefinition)</span>}
            </td>

            <td>
                @if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Edit", new { id = item.Id }) alt="Edit"><img src="~/images/edit_ico.png" /></a>
                }
                - <a href=@Url.Action("Details", new { id = item.Id }) alt="Details"><img src="~/images/details_ico.png" /></a>
                - <a href=@Url.Action("ScanImages", new { id = item.Id }) alt="Details"><img src="~/images/scan_images_icon.png" /></a>
                - <a href=@Url.Action("SignMedicalReport", new { id = item.Id }) alt="Sign Report"><img src="~/images/sign_doc_ico.png" /></a>
            </td>
        </tr>
    }

</table>