JEVEGA_Us_Cliniic/Controllers/ReportTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JEVEGA_Us_Cliniic;

namespace JEVEGA_Us_Cliniic.Controllers
{
    public class ReportTemplatesController : Controller
    {
        private JEVEGA_UsDbEntities db = new JEVEGA_UsDbEntities();

        // GET: ReportTemplates
        public ActionResult Index()
        {
            string usertype = Session["USER_TYPE"].ToString();
            if (usertype == "1")   //-- Admin user ... 
            {
                return View(db.ExamReportTemplates.ToList());
            }
            else { return RedirectToAction("UnauthorizedAccess", "Users"); }

        } //--

        // GET: ReportTemplates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamReportTemplate examReportTemplate = db.ExamReportTemplates.Find(id);
            if (examReportTemplate == null)
            {
                return HttpNotFound();
            }
            return View(examReportTemplate);
        }

        // GET: ReportTemplates/Create
        public ActionResult Create()
        {
            ViewBag.ReportCategories = new SelectList(db.DiagnosticExams, "Id", "ExamName");

            return View();
        }

        // POST: ReportTemplates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ReportCategory,ReportWriteUps,ReportName")] ExamReportTemplate examReportTemplate)
        {
            if (ModelState.IsValid)
            {
                db.ExamReportTemplates.Add(examReportTemplate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ReportCategories = new SelectList(db.DiagnosticExams, "Id", "ExamName");
            }

            return View(examReportTemplate);
        }

        // GET: ReportTemplates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamReportTemplate examReportTemplate = db.ExamReportTemplates.Find(id);
            if (examReportTemplate == null)
            {
                return HttpNotFound();
            }

            ViewBag.ReportCategories = new SelectList(db.DiagnosticExams, "Id", "ExamName");

            return View(examReportTemplate);
        } //--

        // POST: ReportTemplates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ReportCategory,ReportWriteUps,ReportName")] ExamReportTemplate examReportTemplate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(examReportTemplate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(examReportTemplate);
        }

        // GET: ReportTemplates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamReportTemplate examReportTemplate = db.ExamReportTemplates.Find(id);
            if (examReportTemplate == null)
            {
                return HttpNotFound();
            }
            return View(examReportTemplate);
        }

        // POST: ReportTemplates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExamReportTemplate examReportTemplate = db.ExamReportTemplates.Find(id);
            db.ExamReportTemplates.Remove(examReportTemplate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

JEVEGA_Us_Cliniic/Views/ReportTemplates/Create.cshtml
@model JEVEGA_Us_Cliniic.ExamReportTemplate

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>New Report Template</h3></td>
        <td align="right"></td>
    </tr>
</table>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ReportCategory, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ReportCategory, (SelectList)ViewBag.ReportCategories, "- Select a Report Category -", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReportCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReportName, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.ReportName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReportName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReportWriteUps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ReportWriteUps, new { @class = "textarea_report_template", rows = "3" })
                @Html.ValidationMessageFor(model => model.ReportWriteUps, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="line_space"></div>
        <table class="table table-bordered">
            <tr>
                <td>
                    <input type="submit" value="Add Report Template" class="btn btn-default" />
                    &nbsp;
                    <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "ReportTemplates") + "'");" />
                </td>
            </tr>
        </table>

    </div>
}

JEVEGA_Us_Cliniic/Views/ReportTemplates/Delete.cshtml
@model JEVEGA_Us_Cliniic.ExamReportTemplate

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ExamReportTemplate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReportCategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportCategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReportWriteUps)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportWriteUps)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReportName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JEVEGA_Us_Cliniic/Views/ReportTemplates/Details.cshtml
@model JEVEGA_Us_Cliniic.ExamReportTemplate

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}


<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Report Template Details</h3></td>
        <td align="right"></td>
    </tr>
</table>

<div>
    <hr />

    <span class="text_form_value">Report Category : @Html.DisplayFor(model => model.getReportCategoryName)</span>
    <br /><br />

    <span class="text_form_value">Report Name : @Html.DisplayFor(model => model.ReportName)</span>
    <br /><br />

    <span class="text_form_value">Report Write-Ups :</span>
    <br /><br />
    <textarea id="report_writeups" class="textarea_report_template" readonly>@Html.DisplayFor(model => model.ReportWriteUps)</textarea>

</div>


<div class="line_space"></div>
<table class="table table-bordered">
    <tr>
        <td>
            <input type="button" value="Back To List" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "ReportTemplates") + "'");" />
            &nbsp;
            <input type="button" value="Update" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Edit/"+Model.Id, "ReportTemplates") + "'");" />
        </td>
    </tr>
</table>

JEVEGA_Us_Cliniic/Views/ReportTemplates/Edit.cshtml
@model JEVEGA_Us_Cliniic.ExamReportTemplate

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}


<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Update Report Template</h3></td>
        <td align="right"></td>
    </tr>
</table>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ReportCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ReportCategory, (SelectList)ViewBag.ReportCategories, "- Select a Report Category -", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReportCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReportName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReportName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReportName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReportWriteUps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ReportWriteUps, new { @class = "textarea_report_template", rows = "3" })
                @Html.ValidationMessageFor(model => model.ReportWriteUps, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="line_space"></div>
        <table class="table table-bordered">
            <tr>
                <td>
                    <input type="submit" value="Update" class="btn btn-default" />
                    &nbsp;
                    <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "ReportTemplates") + "'");" />
                </td>
            </tr>
        </table>

    </div>
}

JEVEGA_Us_Cliniic/Views/ReportTemplates/Index.cshtml
@model IEnumerable<JEVEGA_Us_Cliniic.ExamReportTemplate>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Diagnostic Report Templates</h3></td>
        <td align="right">
            @{
                if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Create", "ReportTemplates")><img src="~/images/add_icon.png" /></a>
                }
            }
        </td>
    </tr>
</table>


<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.ReportCategory)</th>
        <th>@Html.DisplayNameFor(model => model.ReportName)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.getReportCategoryName)</td>
            <td>@Html.DisplayFor(modelItem => item.ReportName)</td>

            <td>
                @if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Edit", new { id = item.Id }) alt="Edit"><img src="~/images/edit_ico.png" /></a>
                }
                - <a href=@Url.Action("Details", new { id = item.Id }) alt="Details"><img src="~/images/details_ico.png" /></a>

            </td>

        </tr>
    }

</table>