JEVEGA_Us_Cliniic/Controllers/CashDisbursementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using JEVEGA_Us_Cliniic;
using System.Data.SqlClient;
using System.Configuration;

namespace JEVEGA_Us_Cliniic.Controllers
{
    public class CashDisbursementController : Controller
    {
        private JEVEGA_UsDbEntities db = new JEVEGA_UsDbEntities();

        UtilityHelper utHelp = new UtilityHelper();
        public string[] fullMonthName = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };

        // GET: CashDisbursement
        public ActionResult Index()
        {
            if (Session["USER_TYPE"] == null)
            {
                return RedirectToAction("Login", "Users", new { @ReturnUrl = "/CashDisbursement/Index" });
            }

            string query_month = Request.QueryString["mo"];
            string query_year = Request.QueryString["yr"];

            int this_month;
            int this_year;
            if (query_month == null)
            {
                DateTime today = DateTime.Now;
                this_month = today.Month;
                this_year = today.Year;
            }
            else
            {   this_month = Convert.ToInt32(query_month);
                this_year = Convert.ToInt32(query_year);
            }

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            listOfYears = utHelp.CreateListOfYears(this_year);

            List<SelectListItem> listOfMonths = new List<SelectListItem>();
            listOfMonths = utHelp.CreateListMonthNames(this_month);

            ViewBag.YearsList = listOfYears.ToList();
            ViewBag.MonthsList = listOfMonths.ToList();
            ViewBag.DateList = fullMonthName[this_month - 1] + " " + this_year;

            List<CashDisbursement> cashDisbursementList = db.CashDisbursements.Where(c => c.DateSpent.Month == this_month).ToList();

            decimal totalAmount = cashDisbursementList.Sum(a => a.Amount);
            string strTotalCashDisburseAmount = string.Format("{0:0,0.00}", totalAmount);
            ViewBag.TotalCashDisburseAmount = strTotalCashDisburseAmount;

            return View(cashDisbursementList);
        }

        [HttpPost]
        public ActionResult Index(FormCollection formCollection)
        {
            string str_year = formCollection["ListOfYears"];
            int this_year = Convert.ToInt32(str_year);

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            listOfYears = utHelp.CreateListOfYears(this_year);

            string str_month = formCollection["ListOfMonths"];
            int this_month = Convert.ToInt32(str_month);

            List<SelectListItem> listOfMonths = new List<SelectListItem>();
            listOfMonths = utHelp.CreateListMonthNames(this_month);

            ViewBag.YearsList = listOfYears.ToList();
            ViewBag.MonthsList = listOfMonths.ToList();
            ViewBag.DateList = fullMonthName[this_month - 1] + " " + this_year;

            List<CashDisbursement> cashDisbursementList = db.CashDisbursements.Where(c => c.DateSpent.Month == this_month).ToList();

            decimal totalAmount = cashDisbursementList.Sum(a => a.Amount);
            string strTotalCashDisburseAmount = string.Format("{0:0,0.00}", totalAmount);
            ViewBag.TotalCashDisburseAmount = strTotalCashDisburseAmount;

            return View(cashDisbursementList);

        } //--

        // GET: CashDisbursement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CashDisbursement cashDisbursement = db.CashDisbursements.Find(id);
            if (cashDisbursement == null)
            {   return HttpNotFound();  }

            ViewBag.DetailMonth = cashDisbursement.DateSpent.Month.ToString();
            ViewBag.DetailYear = cashDisbursement.DateSpent.Year.ToString();
            ViewBag.imageCashFile = "cashimageref-" + cashDisbursement.Id.ToString() + ".jpg";

            return View(cashDisbursement);
        }

        public ActionResult ViewCashRef(int? id)
        {
            if (id == null)
            {   return new HttpStatusCodeResult(HttpStatusCode.BadRequest);     }

            CashDisbursement cashDisbursement = db.CashDisbursements.Find(id);
            if (cashDisbursement == null)
            { return HttpNotFound(); }

            ViewBag.imageCashFile = "cashimageref-" + cashDisbursement.Id.ToString() + ".jpg";

            return View(cashDisbursement);
        } //-- 

        // GET: CashDisbursement/Create
        public ActionResult Create()
        {
            string usertype = Session["USER_TYPE"].ToString();
            if (!utHelp.CheckAdminAccess(usertype))
            {
                return RedirectToAction("UnauthorizedAccess", "Users");
            }

            ViewBag.ExpenseCategories = new SelectList(db.ExpenseCategories, "Id", "ExpenseCategory1");

            return View();
        }

        // POST: CashDisbursement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ItemDescription,ItemCategory,Amount,DateSpent,ReferenceNo,ItemImage")] CashDisbursement cashDisbursement)
        {
            if (ModelState.IsValid)
            {
                db.CashDisbursements.Add(cashDisbursement);
                db.SaveChanges();
                string month = cashDisbursement.DateSpent.Month.ToString();

                return RedirectToAction("Index", new { mo = month });
            }

            ViewBag.ExpenseCategories = new SelectList(db.ExpenseCategories, "Id", "ExpenseCategory1");

            return View(cashDisbursement);
        }

        // GET: CashDisbursement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {   return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }

            CashDisbursement cashDisbursement = db.CashDisbursements.Find(id);
            if (cashDisbursement == null)
            {   return HttpNotFound();  }

            ViewBag.ExpenseCategories = new SelectList(db.ExpenseCategories, "Id", "ExpenseCategory1");
            return View(cashDisbursement);
        } //--

        // POST: CashDisbursement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ItemDescription,ItemCategory,Amount,DateSpent,ReferenceNo,ItemImage")] CashDisbursement cashDisbursement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cashDisbursement).State = EntityState.Modified;
                db.SaveChanges();
                string month = cashDisbursement.DateSpent.Month.ToString();
                string year = cashDisbursement.DateSpent.Year.ToString();

                return RedirectToAction("Index", new { mo = month, yr = year });
            }
            return View(cashDisbursement);
        }

        // GET: CashDisbursement/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CashDisbursement cashDisbursement = db.CashDisbursements.Find(id);
            if (cashDisbursement == null)
            {
                return HttpNotFound();
            }
            return View(cashDisbursement);
        }

        // POST: CashDisbursement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CashDisbursement cashDisbursement = db.CashDisbursements.Find(id);
            db.CashDisbursements.Remove(cashDisbursement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult UploadCashRef(int id)
        {
            CashDisbursement cashDisbursement = db.CashDisbursements.Find(id);
            if (cashDisbursement == null)
            {
                return HttpNotFound();
            }

            ViewBag.DetailMonth = cashDisbursement.DateSpent.Month.ToString();
            ViewBag.DetailYear = cashDisbursement.DateSpent.Year.ToString();

            return View(cashDisbursement);
        } //==

        [HttpPost]
        public ActionResult UploadCashRefImage([Bind(Include = "Id")] CashDisbursement cashdisburse, HttpPostedFileBase fileCashRef)
        {
            if (fileCashRef != null)
            {
                string fileCashRefImage = "cashimageref-" + cashdisburse.Id.ToString() + ".jpg";
                ViewBag.fileCashRefImage = fileCashRefImage;

                string file_ext = Path.GetExtension(fileCashRef.FileName);
                if (!InvalidFileExtension(file_ext))
                {
                    string path = Server.MapPath("~/CashImages/" + fileCashRefImage);
                    fileCashRef.SaveAs(path);

                    string US_ConnStr = ConfigurationManager.ConnectionStrings["USClinic_ADO"].ConnectionString;
                    using (SqlConnection sqlCon = new SqlConnection(US_ConnStr))
                    {

JEVEGA_Us_Cliniic/Views/CashDisbursement/Create.cshtml
@model JEVEGA_Us_Cliniic.CashDisbursement

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("input").focus(function () {
            $(this).css("background-color", "aliceblue");
        });

        $("input").blur(function () {
            $(this).css("background-color", "white");
        });

        $("select").focus(function () {
            $(this).css("background-color", "aliceblue");
        });

        $("select").blur(function () {
            $(this).css("background-color", "white");
        });

        $("textarea").focus(function () {
            $(this).css("background-color", "aliceblue");
        });

        $("textarea").blur(function () {
            $(this).css("background-color", "white");
        });
    });
</script>

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>New Cash Disbursement</h3></td>
        <td align="right"></td>
    </tr>
</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ItemCategory, (SelectList)ViewBag.ExpenseCategories, "- Select a Category -", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ItemCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateSpent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateSpent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateSpent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReferenceNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReferenceNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReferenceNo, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="line_space"></div>
        <table class="table table-bordered">
            <tr>
                <td>
                    <input type="submit" value="Add Cash Disbursement" class="btn btn-default" />
                    &nbsp;
                    <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "CashDisbursement") + "'");" />
                </td>
            </tr>
        </table>

    </div>
}

JEVEGA_Us_Cliniic/Views/CashDisbursement/Delete.cshtml
@model JEVEGA_Us_Cliniic.CashDisbursement

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CashDisbursement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemCategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemCategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateSpent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateSpent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReferenceNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReferenceNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JEVEGA_Us_Cliniic/Views/CashDisbursement/Details.cshtml
@model JEVEGA_Us_Cliniic.CashDisbursement

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function () {

        $('#cashref').on({
            click: function () {
                $('#cashrefimage').attr('src', '/CashImages/@ViewBag.imageCashFile');
            }
        });
    });

</script>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog" style="width:1024px;">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Cash Reference : @Model.ItemDescription | @Model.Id</h4>
            </div>
            <div class="modal-body"><img id="cashrefimage" src="" class="img-fluid" style="width:980px" /></div>
        </div>
    </div>
</div>


<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Cash Disbursement Details</h3></td>
        <td align="right"></td>
    </tr>
</table>

<div>
    <hr />

    <table class="table_clinic">
        <tr><td colspan="4"><div class="line_space"></div></td></tr>
        <tr>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ItemDescription)</span></td>
            <td>
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.ItemDescription)</span>
            </td>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ItemCategory)</span></td>
            <td>
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.getCategoryName)</span>
            </td>
        </tr>
        <tr>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.Amount)</span></td>
            <td>
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.Amount)</span>
            </td>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.DateSpent)</span></td>
            <td>
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.DateSpent)</span>
            </td>
        </tr>
        <tr>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ReferenceNo)</span></td>
            <td colspan="3">
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.ReferenceNo)</span>
            </td>
        </tr>
        <tr>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ItemImage)</span></td>
            <td colspan="3">
                @{ if (Model.ItemImage == true)
                    {
                        <img src="~/images/cash_expense_ico_lrg.png" id="cashref" data-toggle="modal" data-target="#myModal" class="hand_cursor" border="0" />
                    }
                }
            </td>
        </tr>
    </table>

</div>


<div class="line_space"></div>
<table class="table table-bordered">
<tr>
    <td>
        <input type="button" value="Back To List" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "CashDisbursement", new { mo=ViewBag.DetailMonth, yr=ViewBag.DetailYear }) + "'");" />
    </td>
</tr>
</table>

JEVEGA_Us_Cliniic/Views/CashDisbursement/Edit.cshtml
@model JEVEGA_Us_Cliniic.CashDisbursement

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Edit Cash Disbursement Details</h3></td>
        <td align="right"></td>
    </tr>
</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ItemCategory, (SelectList)ViewBag.ExpenseCategories, "- Select a Category -", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ItemCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateSpent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateSpent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateSpent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReferenceNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReferenceNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReferenceNo, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>

    <div class="line_space"></div>
    <table class="table table-bordered">
        <tr>
            <td>
                <input type="submit" value="Save" class="btn btn-default" />
                &nbsp;
                <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "CashDisbursement", new { mo=ViewBag.EditMonth, yr=ViewBag.EditYear }) + "'");" />
            </td>
        </tr>
    </table>

}

JEVEGA_Us_Cliniic/Views/CashDisbursement/Index.cshtml
@model IEnumerable<JEVEGA_Us_Cliniic.CashDisbursement>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}


<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Cash Disbursement | @ViewBag.DateList</h3></td>
        <td align="right">
            @{
                if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Create", "CashDisbursement")><img src="~/images/add_icon.png" /></a>
                }
            }
            &nbsp;
        </td>
    </tr>
</table>
<div class="div_space20"></div>

<table class="table table-striped">
    <tr>
        <th>@Html.DisplayNameFor(model => model.ItemDescription)</th>
        <th>@Html.DisplayNameFor(model => model.ItemCategory)</th>
        <th style="float:right">@Html.DisplayNameFor(model => model.Amount)</th>
        <th>@Html.DisplayNameFor(model => model.DateSpent)</th>
        <th>@Html.DisplayNameFor(model => model.ReferenceNo)</th>
        <th>@Html.DisplayNameFor(model => model.ItemImage)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.ItemDescription)</td>
            <td>@Html.DisplayFor(modelItem => item.getCategoryName)</td>
            <td align="right">@Html.DisplayFor(modelItem => item.Amount)</td>
            <td>@Html.DisplayFor(modelItem => item.DateSpent)</td>
            <td>@Html.DisplayFor(modelItem => item.ReferenceNo)</td>

            <td>
                @if (item.ItemImage == true)
                {
                    <a href="CashDisbursement/ViewCashRef/@item.Id" onclick="window.open(this.href, 'windowName', 'width=1000, height=700, left=70, top=70, scrollbars, resizable'); return false;">
                        <img src="~/images/cash_expense_ico.png" id="cashref" class="hand_cursor" border="0" />
                    </a>
                }
            </td>

            <td>
                @if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Edit", new { id = item.Id }) alt="Edit"><img src="~/images/edit_ico.png" /></a>
                }
                - <a href=@Url.Action("Details", new { id = item.Id }) alt="Details"><img src="~/images/details_ico.png" /></a>
                - <a href=@Url.Action("UploadCashRef", new { id = item.Id })><img src="~/images/upload_cashref_ico.png" /></a>
            </td>
        </tr>
    }

    <tr>
        <td colspan="2"><span class="text_form_value">TOTAL :</span></td>
        <td align="right"><span class="text_form_value">@ViewBag.TotalCashDisburseAmount</span></td>
        <td colspan="4"></td>
    </tr>

</table>

@using (Html.BeginForm())
{
    <table class="table table-bordered">
    <tr>
        <td nowrap="nowrap">
            @Html.DropDownList("ListOfMonths", (List<SelectListItem>)ViewBag.MonthsList, "- Select an Month -", new { @class = "form-control" })
        </td>
        <td>
            @Html.DropDownList("ListOfYears", (List<SelectListItem>)ViewBag.YearsList, "- Select a Year -", new { @class = "form-control" })
        </td>

        <td><input type="submit" value="Filter by Month/Year" class="btn btn-default" /></td>
    </tr>
    </table>

    <div class="div_space20"></div>
}

JEVEGA_Us_Cliniic/Views/CashDisbursement/UploadCashRef.cshtml
@model JEVEGA_Us_Cliniic.CashDisbursement

@{
    ViewBag.Title = "UploadCashRef";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
<tr>
    <td><h3>Upload Cash Reference Image</h3></td>
    <td align="right"></td>
</tr>
</table>


@using (Html.BeginForm("UploadCashRefImage", "CashDisbursement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <table class="table_clinic">
            <tr><td colspan="4"><div class="line_space"></div></td></tr>
            <tr>
                <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ItemDescription)</span></td>
                <td>
                    <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.ItemDescription)</span>
                </td>
                <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ItemCategory)</span></td>
                <td>
                    <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.getCategoryName)</span>
                </td>
            </tr>
            <tr><td colspan="4"><div class="line_space"></div></td></tr>
            <tr>
                <td><span class="report_fieldvalue_01">Cash Reference Image</span></td>
                <td colspan="3"><input type="file" name="fileCashRef" id="fileCashRef" /></td>
            </tr>

        </table>

    </div>


    <div class="line_space"></div>
    <table class="table table-bordered">
    <tr>
        <td>
            <input type="submit" value="Upload" class="btn btn-default" />
            &nbsp;
            <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "CashDisbursement", new { mo=ViewBag.DetailMonth, yr=ViewBag.DetailYear }) + "'");" />
        </td>
    </tr>
    </table>

}

JEVEGA_Us_Cliniic/Views/CashDisbursement/ViewCashRef.cshtml
@model JEVEGA_Us_Cliniic.CashDisbursement

@{
    ViewBag.Title = "ViewCashRef";
    Layout = "~/Views/Shared/Layout_print_report.cshtml";
}


<table class="table_clinic_pageheader">
<tr>
    <td><h3>Cash Disbursement Reference</h3></td>
</tr>
</table>

<div>

    <table class="table_clinic">
        <tr><td colspan="4"><div class="line_space"></div></td></tr>
        <tr>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ItemDescription)</span></td>
            <td>
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.ItemDescription)</span>
            </td>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ItemCategory)</span></td>
            <td>
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.getCategoryName)</span>
            </td>
        </tr>
        <tr>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.Amount)</span></td>
            <td>
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.Amount)</span>
            </td>
            <td><span class="report_fieldvalue_01">@Html.LabelFor(model => model.DateSpent)</span></td>
            <td>
                <span class="report_fieldvalue_01">@Html.DisplayFor(model => model.DateSpent)</span>
            </td>
        </tr>

        <tr>
            <td colspan="4"><span class="report_fieldvalue_01">@Html.LabelFor(model => model.ItemImage)</span></td>
        </tr>
        <tr>
            <td colspan="4">
                <img src="~/CashImages/@ViewBag.imageCashFile" class="img-responsive" border="0" />
            </td>
        </tr>
    </table>

</div>